name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build no voice policy
      run: docker build no-voice-policy --file no-voice-policy/Dockerfile --tag arisedream/telegram-extras-no-voice-policy:$(date +%s)
