name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  list-extras:
    runs-on: ubuntu-latest
    outputs:
      extra: ${{ steps.set-extras.outputs.extra }}
    
    steps:
    - uses: actions/checkout@v4
    - id: set-extras
      run: echo "::set-output name=extra::$(ls -d */ | cut -f1 -d'/' | jq -R -s -c 'split("\n")[:-1]')"    

  build:
    runs-on: ubuntu-latest
    needs: list-extras
    strategy:
        matrix:
            extra: ${{ fromJson(needs.list-extras.outputs.extra) }}

    steps:
    - name: Build Docker
      run: docker build no-voice-policy --file ${{ matrix.extra }}/Dockerfile --tag arisedream/telegram-extras-${{ matrix.extra }}:$(date +%s)
